config/routes.rb
Rails.application.routes.draw do
  root 'heroes#index'
  resources :heroes
  resources :battles
  resources :firststages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goblin.rb
class Goblin < Monster
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/models/matango.rb
class Matango < Monster
end

app/models/monster.rb
class Monster
  attr_accessor :name, :hp, :attack, :defence, :speed

  def initialize(name: nil, hp: nil, attack: nil, defence: nil, speed: nil)
    @name = name
    @hp = hp
    @attack = attack
    @defence = defence
    @speed = speed
  end

  def normal_attack
    "攻撃#{attack}"
  end

  def power_attack
    "強攻撃#{attack + 50}"
  end
end

app/models/slime.rb
class Slime < Monster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def index
    @hero = Hero.find(1)
    slime = Slime.new(name: "スライム", hp: 50, attack: 50, defence: 50, speed: 40)
    goblin = Goblin.new(name: "ゴブリン",hp: 70, attack: 70, defence: 70, speed: 70)
    matango = Matango.new(name: "マタンゴ",hp: 60, attack: 60, defence: 60, speed: 60)
    @monsters = [slime, goblin, matango]
  end
end

app/controllers/firststages_controller.rb
class FirststagesController < ApplicationController
  def index
    @hero = Hero.find(1)
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  def index
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.new(hero_params)
    if @hero.save
      redirect_to root_path
    else
      redirect_to new_hero_path
    end
  end

  private

  def hero_params
    params.require(:hero).permit(:name, :hp, :mp, :attack, :defence, :magic_attack, :magic_defence, :speed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/firststages_helper.rb
module FirststagesHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/views/battles/index.html.haml
- monster = @monsters.sample #モンスターを一匹呼び出す
.battle_hero_box
  .battle_hero_box_name
    %p.battle_hero_box_name_text#battle_hero_box_name_text
      = @hero.name
  .battle_hero_box_status
    %p.battle_hero_box_status_hp#battle_hero_box_status_hp
      = "H #{@hero.hp}"
    %p.battle_hero_box_status_mp
      = "M #{@hero.mp}"

%div{class: "battle_monster_box", id: "battle_monster_box", data: {attack: monster.normal_attack, defence: monster.defence}}
  .battle_monster_name
    %p.battle_monster_name_text#battle_monster_name_text
      = monster.name
  .battle_monster_image
    = image_tag "slime.png", size: "300x180" if monster.name == "スライム"
    = image_tag "goblin.jpg", size: "300x180" if monster.name == "ゴブリン"
    = image_tag "matango.jpeg", size: "300x180" if monster.name == "マタンゴ"
  .battle_monster_hp
    %p.battle_monster_hp_text#battle_monster_hp_text
      = "H #{monster.hp}"

%footer.battle_footer#battle_footer
  .battle_hero_box#battle_hero_box
    .battle_hero_box_name
      %p.battle_hero_box_name_text
        = @hero.name
    .battle_hero_box_status
      %p{id: "combat", data: {attack: @hero.attack, defence: @hero.defence}}
        たたかう
      %p#escape
        逃げる
= link_to "フィールドに戻る", firststages_path, id: "back_field"

app/views/firststages/index.html.haml
.first_stage
  .first_stage_monsterArea
  .first_stage_hero#first_stage_hero
    = @hero.name[0]

= link_to "戦闘開始", battles_path, id: "battles_path"

app/views/heroes/index.html.haml
%h1.first_time_rpg
  初めてのRPG
%p.game_start
  = link_to "NEW GAME", new_hero_path, class: "game_start_link"
%p.game_start
  = link_to "LOAD GAME", firststages_path, class: "game_start_link"

app/views/heroes/new.html.haml
%h1.hero_create
  勇者の名前を決めよう
%p.hero_name_create_instructions
  名前を入力してください
= form_for @hero, :url => {:controller => :heroes, :action => :create}  do |f|
  .hero_name_text_field
    = f.text_field :name, id: "hero_name_define", class: "hero_name_define"
    = f.hidden_field :hp, value: 100
    = f.hidden_field :mp, value: 100
    = f.hidden_field :attack, value: 100
    = f.hidden_field :defence, value: 100
    = f.hidden_field :magic_attack, value: 100
    = f.hidden_field :magic_defence, value: 100
    = f.hidden_field :speed, value: 100
  .hero_name_submit_box
    = f.submit "名前を決定する", id: "hero_name_define_submit", class: "hero_name_define_submit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RpgApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield